import jsPDF from 'jspdf';
import { AnalysisResult } from '../services/analysis.service';
import { Language, translations } from './i18n';

export function generateReport(result: AnalysisResult, language: Language): void {
  const doc = new jsPDF();
  const t = translations[language];
  const isRtl = language === 'ar';
  
  // Standard simple layout
  const marginX = 20;
  let cursorY = 20;

  // Since standard jsPDF doesn't support Arabic natively without custom fonts, 
  // for this exercise, we will fallback to English if standard rendering fails, 
  // or just use basic ASCII in our PDF.
  // Real world: we'd need to add a TTF font and addFileToVFS for Arabic support.
  // Here we will use standard jsPDF text but stick to English for reliability in the PDF output
  // to prevent garbage text rendering.
  const langToUse = 'en'; // Force EN for PDF standard font compatibility
  const tPdf = translations[langToUse];

  // Header
  doc.setFontSize(22);
  doc.setTextColor(139, 92, 246); // Purple
  doc.text('CYBER INSPECTOR AI - ANALYSIS REPORT', marginX, cursorY);
  
  cursorY += 15;
  doc.setFontSize(12);
  doc.setTextColor(50, 50, 50);
  doc.text(`Report ID: ${result.id}`, marginX, cursorY);
  cursorY += 8;
  doc.text(`Date: ${new Date(result.timestamp).toLocaleString()}`, marginX, cursorY);
  
  cursorY += 15;
  
  // Score
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`${tPdf.threatScore}: ${result.threatScore}/100`, marginX, cursorY);
  cursorY += 8;
  doc.text(`${tPdf.riskLevel}: ${result.riskLevel.toUpperCase()}`, marginX, cursorY);
  
  cursorY += 15;
  
  // Summary
  doc.setFontSize(14);
  doc.setTextColor(139, 92, 246);
  doc.text(tPdf.summary, marginX, cursorY);
  cursorY += 8;
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  const splitSummary = doc.splitTextToSize(result.summary, 170);
  doc.text(splitSummary, marginX, cursorY);
  cursorY += (splitSummary.length * 7) + 10;
  
  // Indicators
  doc.setFontSize(14);
  doc.setTextColor(139, 92, 246);
  doc.text(tPdf.whyDangerous, marginX, cursorY);
  cursorY += 8;
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  result.indicators.forEach(ind => {
    doc.setFont('', 'bold');
    doc.text(`- ${ind.type} (${ind.severity})`, marginX, cursorY);
    doc.setFont('', 'normal');
    cursorY += 6;
    const desc = doc.splitTextToSize(`  ${ind.description}`, 170);
    doc.text(desc, marginX, cursorY);
    cursorY += (desc.length * 7) + 4;
  });
  
  cursorY += 5;
  
  // Recommendations
  doc.setFontSize(14);
  doc.setTextColor(139, 92, 246);
  doc.text(tPdf.recommendations, marginX, cursorY);
  cursorY += 8;
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  result.recommendations.forEach((rec, idx) => {
    const text = doc.splitTextToSize(`${idx + 1}. ${rec}`, 170);
    doc.text(text, marginX, cursorY);
    cursorY += (text.length * 7) + 2;
  });
  
  // Footer
  cursorY = 280;
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text('This report was generated by Cyber Inspector AI. For educational purposes only.', marginX, cursorY);
  
  doc.save(`cyber-inspector-report-${result.id}.pdf`);
}
