export const RESPONSE_LINKS = {
  verifyLink: {
    title: "Verify Link",
    titleAr: "التحقق من الرابط",
    description: "Check if a URL is safe using Tahqaq Service",
    descriptionAr: "تحقق من سلامة الرابط باستخدام خدمة تحقق",
    url: "https://haseen.gov.sa/tahqaq/",
    icon: "Shield",
  },
  reportFraud: {
    title: "Report Financial Fraud",
    titleAr: "الإبلاغ عن الاحتيال المالي",
    description: "Report scams to GOV.SA",
    descriptionAr: "أبلغ عن عمليات الاحتيال المالية إلى المنصة الوطنية",
    url: "https://my.gov.sa/ar/services/538742",
    icon: "AlertTriangle",
  },
  governmentPortal: {
    title: "Government Portal",
    titleAr: "البوابة الحكومية",
    description: "Official cybercrime reporting portal",
    descriptionAr: "بوابة الإبلاغ الرسمية عن الجرائم المعلوماتية",
    url: "https://my.gov.sa/ar/services/398352",
    icon: "Building2",
  },
  securityAwareness: {
    title: "Security Tips",
    titleAr: "نصائح الأمان",
    description: "Learn to protect yourself online",
    descriptionAr: "تعلم كيف تحمي نفسك على الإنترنت",
    url: "https://safety.google/intl/ar_ALL/safety/security-tips/",
    icon: "BookOpen",
  },
  emergencyContacts: {
    title: "Emergency Contacts",
    titleAr: "جهات الاتصال الطارئة",
    description: "Contact National Cybersecurity Authority immediately",
    descriptionAr: "تواصل فوراً مع الهيئة الوطنية للامن السيبراني",
    url: "https://nca.gov.sa/ar/contact-us/",
    icon: "Phone",
  },
};
